### ISSUE TITLE
How to build it in windows by mingw?

### ISSUE THREAD

**Issue by bumagh** [NippleOfAnApe/rpg-rts-snake#1]
How to build it in windows by mingw?

**Comment by NippleOfAnApe** [comment]
Hm, I actually need to check it on my Windows system, and see how I would compile it with CMake or just Make.

**Comment by NippleOfAnApe** [comment]
but currently I am trying to create the same things but in Bevy gaming library, but in Rust. (and also how to cross-compile it to Windows.)

**Comment by NippleOfAnApe** [comment]
> How to build it in windows by mingw?

1. Git clone this repo and navigate to ```src/``` (in msys32 shell)

You need to have a raylib compiled as static library. If you don't know what this is, check ray's [working on windows](https://github.com/raysan5/raylib/wiki/Working-on-Windows) video.

2. just run ```make install``` and it will create an executable.

3. To add  new source files or libraries, simply add them in the end of a Makefile

**Comment by NippleOfAnApe** [comment]
Actually I not `make` but ```mingw32-make PLATFORM=PLATFORM_DESKTOP```

**Comment by bumagh** [comment]
Ok,it works
